name: Build on pull and depoly on push
on: 
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: build on pull request        
        run: echo " this is build job on pull request"
  depoly:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: deploy on push request to main        
        run: echo " this deploy job on push request to main branch"
