 name: Hello World
 on: 
   push: 
     branches: 
       - main
 jobs:
   Build:
     runs-on: ubuntu-latest
     steps:
       - name: build step
         run: |
           echo "Hello it's step Build step, variable ${{vars.MY_NAME}} secrete ${{secrets.MY_PASSWORD}}"
          
         
   
   
