name: demo outputs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      variable1: ${{steps.step1.outputs.version}}
    steps:
      - name: step one
        id: step1
        run: echo "version=0.1" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy step to print version passed by build
        run: echo " depoly with version ${{needs.build.outputs.variable1}} "
    
